version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_shared_network_tfm

  db-container:
    build:
      context: ./dockerfiles
      dockerfile: db_dockerfile
    environment:
      SA_PASSWORD: password12345678A
      ACCEPT_EULA: Y
      MSSQL_DB: tfm_lesiones
      MSSQL_USER: scraper
      MSSQL_PASSWORD: scraper1234A
    ports:
      - "1433:1433"  # Solo se necesita mapear un puerto para la base de datos
    volumes:
      - ./sql-data:/var/opt/mssql
    networks:
      - my_shared_network_tfm

networks:
  my_shared_network_tfm:
    external: true