version: '3.7'

services:
  crawler_jugadores:
    build:
      context: ./
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - GROUP_NAME=jugadores_spider_redis
      - INSTANCE_TYPE=regular  

    command: scrapy crawl jugadores_spider_redis
    networks:
      - my_shared_network_tfm

  crawler_jugadores_db_reader_writer:
    build:
      context: ./
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - GROUP_NAME=jugadores_spider_redis
      - INSTANCE_TYPE=rw  

    command: scrapy crawl jugadores_spider_redis
    networks:
      - my_shared_network_tfm

networks:
  my_shared_network_tfm:
    external: true